const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const studentController = require('../controllers/studentController');
const paymentController = require('../controllers/paymentController');
const { protect } = require('../middlewares/authMiddleware');
const { studentOnly, checkStudentPayment } = require('../middlewares/roleMiddleware');
const { validateReservation } = require('../middlewares/validationMiddleware');
const { uploadProfilePicture } = require('../middlewares/uploadMiddleware');
router.get('/payment/verify/:reference', paymentController.verifyPayment);
router.use(protect, studentOnly);
router.get('/profile', authController.getProfile);
router.put('/profile', authController.updateProfile);
router.patch('/profile', studentController.updateProfile);
router.post('/profile/picture', uploadProfilePicture, studentController.uploadProfilePicture);
router.get('/dashboard', studentController.getDashboard);
router.get('/alerts', studentController.getAlerts);
router.get('/notifications', studentController.getNotifications);
router.post('/notifications/read', studentController.markNotificationsRead);
router.get('/notifications/settings', studentController.getNotificationSettings);
router.patch('/notifications/preferences', studentController.updateNotificationPreferences);
router.post('/notifications/devices', studentController.registerPushDevice);
router.delete('/notifications/devices', studentController.unregisterPushDevice);
router.get('/invitations/history', studentController.getInvitationHistory);
router.get('/hostels', studentController.getAvailableHostels);
router.get('/hostels/:hostelId/rooms', studentController.getAvailableRooms);
router.get('/rooms/:roomId/bunks', studentController.getAvailableBunks);
router.post('/reserve', validateReservation, studentController.reserveRoom);
router.post('/reservations', studentController.createReservation);
router.delete('/reservations/:reservationId', studentController.cancelReservation);
router.get('/reservation', studentController.getReservation);
router.post('/reservation/invite-preview', studentController.previewReservationInvite);
router.post('/reservation/respond', studentController.respondToReservationInvite);
router.post('/reservation/members', studentController.addGroupMembers);
router.patch('/reservations/:reservationId/members', studentController.addGroupMembers);
router.get('/payment/amount', paymentController.getPaymentAmount);
router.get('/payment/status', paymentController.getPaymentStatus);
router.post('/payment/initialize', paymentController.initializePayment);
router.post('/payment/verify', paymentController.verifyPayment);
router.post('/payment/verify-code', paymentController.verifyPaymentCode);
router.post('/payment/resend-code', paymentController.resendPaymentCode);
module.exports = router;
